# Generated by Django 3.0.3 on 2020-05-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200519_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='banner_image_url',
            field=models.URLField(default='https://images.pexels.com/photos/981781/pexels-photo-981781.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', help_text='Provide a banner image for your post'),
        ),
    ]
